main: mrq.plugin.minecraft.move.WarpPlate
name: WarpPlate
author: R
version: 1.3.1
description: You can WARP anywhere if you set WARP PLATE somewhere!

commands:
    WarpPlate:
        description: Warp Plate Commands.
    /WarpPlate:
        description: Warp Plate Commands.
    wp:
        description: Warp Plate Commands.
    /wp:
        description: Warp Plate Commands.